"""Added address field to ContactModel

Revision ID: 234697ff5aff
Revises: 6c96bd804354
Create Date: 2025-04-01 00:31:54.204330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234697ff5aff'
down_revision: Union[str, None] = '6c96bd804354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('extra_info', sa.String(), nullable=True))
    op.alter_column('contacts', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_unique_constraint(None, 'contacts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.alter_column('contacts', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('contacts', 'extra_info')
    # ### end Alembic commands ###
